sudo: false
language: python
services:
  - memcached
  - postgresql
  - redis-server
python:
  - "2.7"
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
deploy:
  provider: pypi
  user: getsentry
  password:
    secure: NMwOI1H9arp2vbgaidx9OY6y8990hiu0WsHtowEvEdGKXNzAQcy0sW3SoKcB6FN0bk11xhj49+5C++KAwMYwE/SL8Y5OoZ1/iYVI4/XlWNukr+1/pfPKVMgw3v5W+pL5Ba9TBdFfIoFPNYUDPLItSSjg94Bm95034gBkYWC5Hl0=
  on:
    tags: true
  distributions: 'sdist bdist_wheel'
env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
install:
  - make develop
script:
  - PYFLAKES_NODOCTEST=1 flake8 src
  - py.test
